#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: $0 <brightness_value>"
    exit 1
fi

new_brightness="$1"
status_brightness=$(cat /sys/class/backlight/intel_backlight/device/status)
max_brightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)
actual_brightness=$(cat /sys/class/backlight/intel_backlight/actual_brightness)


# Check if the new brightness is within the allowed range
if [ "$new_brightness" -gt "$max_brightness" ]; then
    new_brightness=$max_brightness
elif [ "$new_brightness" -lt 0 ]; then
    # Subtract the absolute value of the negative brightness from the current brightness
    new_brightness=$(($actual_brightness + $new_brightness))
else
    # Add positive brightness value to the current brightness
    new_brightness=$(($actual_brightness + $new_brightness))
fi

# Ensure new brightness is within the bounds
if [ "$new_brightness" -lt 0 ]; then
    new_brightness=1000
elif [ "$new_brightness" -gt "$max_brightness" ]; then
    new_brightness=$max_brightness
fi

# Update the brightness
echo "$new_brightness" | sudo tee /sys/class/backlight/intel_backlight/brightness

exit 0
